Задание 4.1. Адаптивная сетка для главной страницы
htmlacademy-adaptive/512667-sedona-24 pull request #6
Opened 2021-12-04 21:57 UTC by radamid

2021-12-05 17:04 UTC, andreysgra requested changes
По заданию всё выполнено хорошо, а перечисленные ниже замечания носят в большей степени рекомендательный характер.

2021-12-05 17:04 UTC, andreysgra commented on source/less/blocks/site-list.less
> +  }
Можно не "колдовать" с размером отступов второго и третьего элемента, а задать только `margin-left: auto` у третьего.

С точки зрения переполнения контента, если пунктов меню окажется больше, чем в макете, лучше использовать формулу `:nth-child(4n+x)` где `x` - порядковый номер элемента. Например для третьего пункта меню будет `:nth-child(4n+3)`.

2021-12-05 18:28 UTC, radamid commented on source/less/blocks/advantages-list.less
> +  max-width: 1200px;
1. Удаление свойства **width: 100%;** убило разметку на планшете и десктопе. 
2. Свойство **max-width: 1200px;**, возможно, лишнее, но пусть будет - никому не мешает.

2021-12-05 18:37 UTC, radamid commented on source/less/blocks/advantages.less
> +}
Основная нагрузка лежит на свойстве **flex-direction: column;**, удерживая блоки в одной колонке. Чтобы потом внутри использовать строчное направление для  **.advantages__list {flex-direction: row;}** без оглядки.

2021-12-05 18:38 UTC, radamid commented on source/less/blocks/main-advantages.less
> +}
О пользе уже поспорил.

2021-12-05 18:42 UTC, radamid commented on source/less/blocks/page-header.less
> +  display: grid;
В критерии [Б6](https://up.htmlacademy.ru/adaptive/24/criteries#b6) рекомендуется "Гриды используются для основных структурных блоков страницы (шапка, главный контент, подвал)".

2021-12-05 18:43 UTC, radamid commented on source/less/blocks/page-main.less
> +  display: grid;
[Б6](https://up.htmlacademy.ru/adaptive/24/criteries#b6)

2021-12-05 18:47 UTC, radamid commented on source/less/blocks/site-list.less
> +    flex-basis: 239px;
Делится хорошо, но меню навигации на десктопе разваливается.

2021-12-05 18:50 UTC, radamid commented on source/less/blocks/site-list.less
> +  }
За подсказку спасибо. Исправил.

2021-12-05 19:20 UTC, andreysgra commented on source/less/blocks/page-header.less
> +  display: grid;
Рекомендуется ≠ нужно. Не знаю, отображается ли у вас этот блок или он виден только наставнику, но на всякий случай приведу его здесь
![image](https://user-images.githubusercontent.com/17790771/144760340-6ee4c027-26ee-43db-91fe-9aa0fa02ad17.png)

У вас кроме `display: grid` не указано ничего - нет хотя бы шаблона для колонок. Отключение `display: grid` ничего не меняет в раскладке, так как по умолчанию построение блоков в `grid` аналогично построению `block`. Если вы в дальнейшем будете использовать свойства `grid` для того чтобы расположить логотип - то использование CSS Grid будет оправдано.

2021-12-05 19:53 UTC, andreysgra commented on source/less/blocks/advantages-list.less
> +  max-width: 1200px;
Здесь проблема лежит глубже и если сказать в двух словах, то она происходит от этой проблемы: `flex-basis` ≠ `width` . Свойство `flex-basis` задаёт базовый размер флекс элемента по основной оси. Если `width` не указан, то `flex-basis` опирается на ширину, посчитанную по контенту.

Блок `main-advantages` является флекс контейнером и мы знаем, что если явно не указать значение `width` контейнера, то оно будет равно ширине его контента. Внутри этого блока есть 2 элемента: `.main-advantages__image` и `.main-advantages__wrapper`. Свойство `width` у них не указано, а вместо него есть значение для `flex-basis`, но это базовый размер элемента и при отсутствии `width` он равен ширине контента. Внутри `.main-advantages__image` есть только изображение ширина которого 320px, соответственно ширина контента явно меньше 800px. Следом за блоком второй причины `.main-advantages` идут блоки `.additional-advantages` и все эти блоки являются флекс элементами общего флекс контейнера `.advantages-list`. Так как ширина контента в `.main-advantages__image` составляет 320px, то размер этого элемента можно сжать и вместить в эту же флекс строку следующий флекс элемент `.additional-advantages` ширина которого 400px. По этой самой причине и ломается сетка, если убрать `width: 100%` у `.advantages-list__item`. Почему не происходит этого в блоке с первой причиной, хотя там точно такие же параметры, что и во второй? Дело в том, что за блоком первой причины следует блок второй причины, ширина которого не позволяет сжать контент первого блока до такой степени, чтобы втиснуться в первую флекс строку.

Поэтому лучше вместо `flex-basis` задать ширину с помощью `width`.

2021-12-05 20:04 UTC, andreysgra commented on source/less/blocks/advantages.less
> +}
Ещё раз, но более подробно: вы сделали секцию `.advantages` флекс контейнером. Внутри секции есть только 2 HTML элемента - **h2** и `ol`. В упрощённом виде разметка такая:
```
<section class="page-main__advantages advantages">
  <h2 class="advantages__main-title"></h2>

  <ol class="advantages__list advantages-list"></ol>

</section>
```

По умолчанию элементы `<h2>` и `<ol>` имеют блочный бокс, то есть свойство `display` у них равно `block`. Это стандартная блочная модель - блок занимает всю доступную ширину, но даже если его ширина меньше ширины родительского блока, то на эту линию другой блок перейти не может. Блоки идут друг под другом, как монолит. По макету мы видим, что заголовок располагается на одной линии, а нижележащий контент, список, на другой линии - под заголовком. И тут очевидно, что идеально подходит стандартная блочная модель.

По умолчанию `display: flex` выстраивает флекс элементы вдоль главной оси. Но вам это не нужно и вы поворачиваете главную ось с помощью `flex-direction: column`, тем самым эмулируя блочную модель.

2021-12-06 10:43 UTC, radamid commented on source/less/blocks/advantages-list.less
> +  max-width: 1200px;
Теперь увидел суть проблемы с использованием **flex-basis**. Спасибо, исправил.

2021-12-06 12:18 UTC, merged